name: 🚀 Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy non-PHP files for GitHub Pages
        run: |
          mkdir temp_deploy
          find . -type f ! -name "*.php" ! -name "config.json" ! -path "./.git/*" ! -path "./.github/*" ! -path "./.idea/*" -exec cp --parents {} temp_deploy/ \;

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: temp_deploy
          branch: gh-pages
          clean: true

      - name: Deploy PHP files to FTP
        uses: modern-dev/ftp-mirror@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./"
          remote_dir: "./secret-santa"
          delete: "false"
          include: "*.php"
          exclude: ".github/ .idea/ .git/ Readme.md .gitignore config.json"